---
- name: Deploy Nginx Web Server
  hosts: webservers
  become: true
  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
      tags: install

    - name: Ensure Nginx is installed (Debian/Ubuntu)
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"
      tags: install

    - name: Ensure Nginx service is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      tags: service

    - name: Deploy a custom index.html file
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Welcome to Nginx</title>
          </head>
          <body>
              <h1>Deployed via Ansible</h1>
          </body>
          </html>
        owner: root
        group: root
        mode: '0644'
      tags: customize

    - name: Ensure firewall allows HTTP traffic (optional)
      ansible.builtin.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_os_family == "RedHat"
      tags: firewall

    - name: Ensure UFW allows HTTP traffic (optional)
      ansible.builtin.ufw:
        rule: allow
        name: "Nginx Full"
      when: ansible_os_family == "Debian"
      tags: firewall

      #test2
