name: Terraform Pre-Merge Validation

on:
  pull_request:
    branches:
      - main  # Trigger on all branches
  workflow_dispatch:  # Allow manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    name: Validate Terraform for Environment
    env:
      BASE_DIR: IAC  # Base directory for environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Changed Directory
        id: env
        run: |
          # Identify the changed directory under IAC (dev, staging, production)
          CHANGED_DIR=$(git diff --name-only origin/main | grep "^${BASE_DIR}/" | cut -d '/' -f2 | uniq)
          echo "ENVIRONMENT=$CHANGED_DIR" >> $GITHUB_ENV
          echo "Changed environment: $CHANGED_DIR"

      - name: Set up AWS Credentials for Central Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::891377304437:role/Github-access
          aws-region: ca-central-1

      - name: Assume Role for Environment
        id: assume
        run: |
          case $ENVIRONMENT in
            dev)
              echo "ROLE_ARN=arn:aws:iam::724772074988:role/TerraformExecutionRole" >> $GITHUB_ENV
              ;;
            staging)
              echo "ROLE_ARN=arn:aws:iam::257394485697:role/TerraformExecutionRole" >> $GITHUB_ENV
              ;;
            production)
              echo "ROLE_ARN=arn:aws:iam::891377304437:role/Github-access" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown environment: $ENVIRONMENT"
              exit 1
              ;;
          esac
          echo "Using role: $ROLE_ARN"

      - name: Configure AWS for Environment Role
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ca-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        working-directory: ${{ env.BASE_DIR }}/${{ env.ENVIRONMENT }}
        run: terraform init

      - name: Validate Terraform
        working-directory: ${{ env.BASE_DIR }}/${{ env.ENVIRONMENT }}
        run: terraform validate

      - name: Plan Terraform Changes
        working-directory: ${{ env.BASE_DIR }}/${{ env.ENVIRONMENT }}
        run: terraform plan
