name: Terraform Pre-Merge Validation

on:
  pull_request:
    branches:
      - main  # Trigger only on PRs targeting main
  workflow_dispatch:  # Allow manual triggering if needed

permissions:
  id-token: write
  contents: read  # Required for checkout

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    env:
      BASE_DIR: IAC  # Base directory for environments

    steps:
      # Step 1: Check out the code with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      # Step 2: Determine which directory (environment) has changed
      - name: Determine Changed Directory
        id: env
        run: |
          # Fetch the main branch if it doesn't exist locally
          git fetch origin main || echo "No remote main branch found. Skipping fetch."

          # Find which environment (dev, staging, production, ca-central-1) has changed
          CHANGED_DIR=$(git diff --name-only origin/main HEAD | grep "^${BASE_DIR}/" | cut -d '/' -f2 | uniq)

          if [ -z "$CHANGED_DIR" ]; then
            echo "No changes detected in the environment directories."
            exit 1
          fi

          echo "ENVIRONMENT=$CHANGED_DIR" >> $GITHUB_ENV
          echo "Detected environment: $CHANGED_DIR"

      # Step 3: Debug the detected environment
      - name: Debug Environment
        run: |
          echo "Environment: $ENVIRONMENT"

      # Step 4: Set up AWS Credentials for Central Role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::891377304437:role/Github-access
          aws-region: ca-central-1

      # Step 5: Debug AWS Identity
      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      # Step 6: Test OIDC Role Assumption Directly
      - name: Test OIDC Role Assumption
        run: |
          aws sts assume-role-with-web-identity \
            --role-arn arn:aws:iam::891377304437:role/Github-access \
            --role-session-name test-session \
            --web-identity-token $ACTIONS_ID_TOKEN_REQUEST_TOKEN \
            --duration-seconds 900

      # Step 7: Debug AWS Environment Variables
      - name: Debug AWS Environment Variables
        run: env | grep AWS

      # Step 8: Debug OIDC Token
      - name: Debug OIDC Token
        run: |
          curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com"
